version: "3.1"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: exampledb
    ports:
      - "3306:3306"
    volumes:
      - /Users/wj/dockerdata/mysql_sample:/var/lib/mysql

volumes:
  mysql_data:
