version: "3.1"

services:
  mongo:
    image: mongo
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    ports:
      - "27017:27017"
    volumes:
      - /Users/wj/dockerdata/mongo_sample:/data/db
